---
application:
  name: "randomanga"
  project: "Rmg"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "randomanga"
  version: "4.4"
routers:
- name: "main-randomanga"
  routes:
  - application_name: "randomanga"
    paths:
    - "/*"
