name: Deploy

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to randomanga.net
              uses: appleboy/ssh-action@master
              with:
                  username: ${{secrets.USERNAME}}
                  host: ${{secrets.HOST}}
                  key: ${{secrets.SSHKEY}}
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd apps/randomanga/client
                      git pull
                      npm run build
                      cd .. 
                      cd server-ts/ 
                      npm run build
