name: Build & Deploy
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy app
              uses: appleboy/ssh-action@v0.1.2
              with:
                  host: ${{secrets.HOST}} # IP address of the server you wish to ssh into
                  key: ${{secrets.KEY}} # Private or public key of the server
                  username: ${{ secrets.USERNAME }} # User of the server you want to ssh into

                  script: |
                      cd apps/randomanga &&
                      cd client &&
                      npm run build &&
                      cd ../server-ts &&
                      npm run build &&
                      pm2 restart all &&
                      echo 'Deployment successful'
